name: fitmind
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # For making HTTP requests to your Python backend
  http: ^0.13.5

  # Basic icons for iOS-style apps
  cupertino_icons: ^1.0.8

  # Firebase core and services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules for Flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
